config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root "static_pages#home"

  get    "login",  to: "sessions#new"
  post   "login",  to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  get "signup", to: "users#new"
  resources :users, only: [:index, :show, :edit, :create, :update, :destroy] do
    member do
      get :following
      get :followers
    end
  end
  resources :tweets,        only: [:index, :create, :destroy]
  resources :relationships, only: [:create, :destroy]

  get "help",    to: "static_pages#help"
  get "about",   to: "static_pages#about"
  get "contact", to: 'static_pages#contact'

  match "*path" => "application#routing_error", via: :all
end

app/views/layouts/_footer.html.erb
<hr>
<footer class="footer">
  <%= link_to "Help", help_path %>
  <%= link_to "About", about_path  %>
  <%= link_to "Contact", contact_path %>
</footer>

app/views/layouts/_header.html.erb
<div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <%= link_to "TweeKO", root_path, class: "navbar-brand"  %>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span> 
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right header-menu">
        <% if logged_in? %>
          <li>
            <%= link_to users_path do %>
              <%= icon("users") %>
              <span>Users</span>
            <% end %>
          </li>
          <li>
            <%= link_to current_user do %>
              <%= icon("user") %>
              <span>Profile</span>
            <% end %>
          </li>
          <li>
            <%= link_to tweets_path do %>
              <%= icon("comment") %>
              <span>Tweeks</span>
            <% end %>
          </li>
          <li>
            <%= link_to edit_user_path(current_user) do %>
              <%= icon("cog") %>
              <span>Setting</span>
            <% end %>
          </li>
          <li>
            <%= link_to logout_path, method: "delete" do %>
              <%= icon("sign-out") %>
              <span>Log out</span>
            <% end %>
          </li>
        <% else %>
          <% unless params[:controller] == 'static_pages' %> 
            <li>
              <%= link_to users_path do %>
                <%= icon("users") %>
                <span>Users</span>
              <% end %>
            </li>
            <li>
              <%= link_to tweets_path do %>
                <%= icon("comment") %>
                <span>Tweeks</span>
              <% end %>
            </li>
            <li>
              <%= link_to login_path do %>
                <%= icon("sign-in") %>
                <span>Sign in</span>
              <% end %>
            </li>
          <% end %>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all" %>
    <%= stylesheet_pack_tag "application" %>
    <%= javascript_pack_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>